import { useState } from 'react';
import { Plus, X, Play, Loader2, Microscope, Sparkles, Check } from 'lucide-react';
import { DismissableTip } from '@/components/DismissableTip';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import type { ChunkerOptions } from '@/lib/layout-chunker';

interface ExpandedQuery {
  keyword: string;
  isOriginal: boolean;
  selected: boolean;
}

interface AnalyzeTabProps {
  hasChunks: boolean;
  keywords: string[];
  onKeywordsChange: (keywords: string[]) => void;
  chunkerOptions: ChunkerOptions;
  onOptionsChange: (options: ChunkerOptions) => void;
  onAnalyze: () => void;
  isAnalyzing: boolean;
  progress: number;
  onGoToContent: () => void;
}

export function AnalyzeTab({
  hasChunks,
  keywords,
  onKeywordsChange,
  chunkerOptions,
  onOptionsChange,
  onAnalyze,
  isAnalyzing,
  progress,
  onGoToContent,
}: AnalyzeTabProps) {
  const [newQuery, setNewQuery] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [expandedQueries, setExpandedQueries] = useState<ExpandedQuery[]>([]);
  const [fanoutOpen, setFanoutOpen] = useState(true);

  const addQuery = () => {
    if (newQuery.trim() && !keywords.includes(newQuery.trim())) {
      onKeywordsChange([...keywords, newQuery.trim()]);
      setNewQuery('');
    }
  };

  const removeQuery = (index: number) => {
    onKeywordsChange(keywords.filter((_, i) => i !== index));
  };

  const handleGenerateFanout = async () => {
    if (!newQuery.trim()) {
      toast.error('Enter a query first');
      return;
    }

    setIsGenerating(true);
    setExpandedQueries([]);

    try {
      const { data, error } = await supabase.functions.invoke('optimize-content', {
        body: {
          type: 'suggest_keywords',
          content: `Generate semantically related search queries for: "${newQuery.trim()}"
          
Context: This is for testing RAG retrieval. Generate exactly 24 related queries that capture different ways users might search for similar content.

Include:
- Direct synonyms and alternative phrasings
- More specific sub-topics
- Related concepts and terminology
- Common alternative terms and jargon
- Different question formats users might ask
- Long-tail variations

Return exactly 24 diverse related queries. Do not limit word count - queries can be as long as needed to be meaningful.`,
        },
      });

      if (error || data?.error) {
        throw new Error(data?.error || error?.message);
      }

      const suggestions = data.result?.keywords?.map((k: { keyword: string }) => k.keyword) || [];
      
      // Create expanded queries: primary + up to 24 generated (25 total)
      // Select first 14 generated by default (15 total with primary)
      const expanded: ExpandedQuery[] = [
        { keyword: newQuery.trim(), isOriginal: true, selected: true },
        ...suggestions.slice(0, 24).map((s: string, idx: number) => ({
          keyword: s,
          isOriginal: false,
          selected: idx < 14, // Select first 14 (so 15 total with primary)
        })),
      ];

      setExpandedQueries(expanded);
      toast.success(`Generated ${expanded.length - 1} related queries`);
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate variations');
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleExpandedQuery = (keyword: string) => {
    setExpandedQueries(prev =>
      prev.map(q =>
        q.keyword === keyword ? { ...q, selected: !q.selected } : q
      )
    );
  };

  const applyExpandedQueries = () => {
    const selected = expandedQueries
      .filter(q => q.selected)
      .map(q => q.keyword)
      .filter(k => !keywords.includes(k));
    
    onKeywordsChange([...keywords, ...selected]);
    setExpandedQueries([]);
    setNewQuery('');
    toast.success(`Added ${selected.length} queries`);
  };

  const clearExpandedQueries = () => {
    setExpandedQueries([]);
  };

  const selectAllQueries = () => {
    setExpandedQueries(prev => prev.map(q => ({ ...q, selected: true })));
  };

  const deselectAllQueries = () => {
    setExpandedQueries(prev => prev.map(q => ({ ...q, selected: false })));
  };

  if (!hasChunks) {
    return (
      <div className="flex-1 flex items-center justify-center p-4">
        <div className="empty-state">
          <Microscope size={48} strokeWidth={1} />
          <h3>Chunk your content first</h3>
          <p>Go to the Content tab and click "Chunk It, Daddy"</p>
          <button className="btn-secondary" onClick={onGoToContent}>
            Go to Content
          </button>
        </div>
      </div>
    );
  }

  const canAnalyze = keywords.some(k => k.trim()) && !isAnalyzing;
  const selectedCount = expandedQueries.filter(q => q.selected).length;

  return (
    <div className="flex-1 overflow-auto p-4 md:p-6 bg-background">
      <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-4 md:gap-6">
        {/* Left: Queries */}
        <div className="panel">
          <div className="panel-header">
            <h3>Queries</h3>
          </div>

          <DismissableTip tipId="analyze-queries" className="mb-2">
            Enter the exact search queries your audience will ask Google. Use "Run Fanout" to generate related questions.
          </DismissableTip>

          {/* Add Query Input */}
          <div className="flex flex-col sm:flex-row gap-2">
            <Input
              value={newQuery}
              onChange={(e) => setNewQuery(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault();
                  addQuery();
                }
              }}
              placeholder="Enter search query..."
              className="flex-1 moonbug-input"
            />
            <div className="flex gap-2">
              <button
                onClick={addQuery}
                disabled={!newQuery.trim()}
                className="btn-secondary flex-1 sm:flex-none"
              >
                <Plus className="h-4 w-4" />
              </button>
              <button
                onClick={handleGenerateFanout}
                disabled={!newQuery.trim() || isGenerating}
                className="btn-secondary gap-1.5 flex-1 sm:flex-none"
                title="Generate related query variations"
              >
                {isGenerating ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Sparkles className="h-4 w-4" />
                )}
                <span className="text-xs">Run Fanout</span>
              </button>
            </div>
          </div>

          {/* Fanout Expanded Queries */}
          {expandedQueries.length > 0 && (
            <Collapsible open={fanoutOpen} onOpenChange={setFanoutOpen}>
              <div className="border border-accent/30 rounded-lg p-3 bg-accent/5 space-y-3">
                <CollapsibleTrigger asChild>
                  <button className="flex items-center justify-between w-full text-sm font-medium text-foreground">
                    <span>Related Queries ({selectedCount} of {expandedQueries.length} selected)</span>
                    <Sparkles className="h-4 w-4 text-accent" />
                  </button>
                </CollapsibleTrigger>

                <CollapsibleContent className="space-y-3">
                  {/* Select/Deselect All */}
                  <div className="flex items-center gap-2 text-xs">
                    <button
                      onClick={selectAllQueries}
                      className="text-primary hover:underline"
                    >
                      Select All
                    </button>
                    <span className="text-muted-foreground">|</span>
                    <button
                      onClick={deselectAllQueries}
                      className="text-muted-foreground hover:text-foreground"
                    >
                      Deselect All
                    </button>
                  </div>

                  <div className="space-y-2 max-h-[300px] overflow-y-auto">
                    {expandedQueries.map((query) => (
                      <label
                        key={query.keyword}
                        className="flex items-start gap-2 cursor-pointer p-2 rounded-md hover:bg-background/50"
                      >
                        <Checkbox
                          checked={query.selected}
                          onCheckedChange={() => toggleExpandedQuery(query.keyword)}
                          className="mt-0.5"
                        />
                        <span className="text-sm flex-1">{query.keyword}</span>
                        {query.isOriginal && (
                          <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4">
                            primary
                          </Badge>
                        )}
                      </label>
                    ))}
                  </div>

                  <div className="flex items-center gap-2">
                    <button onClick={applyExpandedQueries} className="btn-primary flex-1 h-8 text-sm">
                      <Check className="h-3.5 w-3.5 mr-1.5" />
                      Apply {selectedCount} Selected
                    </button>
                    <button
                      onClick={clearExpandedQueries}
                      className="btn-secondary h-8"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                </CollapsibleContent>
              </div>
            </Collapsible>
          )}

          {/* Query List */}
          <div className="flex-1 space-y-2 max-h-[250px] overflow-y-auto">
            {keywords.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-8">
                Add queries to test retrieval relevance
              </p>
            ) : (
              keywords.map((query, i) => (
                <div
                  key={i}
                  className="flex items-center gap-2 p-2 bg-background border border-border rounded-md"
                >
                  <span className="flex-1 text-sm truncate">{query}</span>
                  <button
                    onClick={() => removeQuery(i)}
                    className="icon-button h-6 w-6"
                  >
                    <X className="h-3 w-3" />
                  </button>
                </div>
              ))
            )}
          </div>

          {/* Analyze Button */}
          <button
            onClick={onAnalyze}
            disabled={!canAnalyze}
            className="btn-primary w-full"
          >
            {isAnalyzing ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <Play className="h-4 w-4" />
                Run Analysis
              </>
            )}
          </button>

          {isAnalyzing && (
            <div className="space-y-2">
              <Progress value={progress} className="h-1" />
              <p className="text-xs text-muted-foreground text-center">
                Generating embeddings and calculating similarity...
              </p>
            </div>
          )}
        </div>

        {/* Right: Settings */}
        <div className="panel">
          <div className="panel-header">
            <h3>Chunking Settings</h3>
          </div>

          <div className="space-y-6">
            {/* Max Chunk Size */}
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <Label className="text-sm font-medium">Max chunk size</Label>
                <span className="text-xs text-muted-foreground font-mono">
                  {chunkerOptions.maxChunkSize} tokens
                </span>
              </div>
              <Slider
                value={[chunkerOptions.maxChunkSize]}
                onValueChange={([value]) =>
                  onOptionsChange({ ...chunkerOptions, maxChunkSize: value })
                }
                min={128}
                max={1024}
                step={64}
                className="w-full"
              />
            </div>

            {/* Chunk Overlap */}
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <Label className="text-sm font-medium">Chunk overlap</Label>
                <span className="text-xs text-muted-foreground font-mono">
                  {chunkerOptions.chunkOverlap} tokens
                </span>
              </div>
              <Slider
                value={[chunkerOptions.chunkOverlap]}
                onValueChange={([value]) =>
                  onOptionsChange({ ...chunkerOptions, chunkOverlap: value })
                }
                min={0}
                max={128}
                step={8}
                className="w-full"
              />
            </div>

            {/* Heading Cascade */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label className="text-sm font-medium">Heading cascade</Label>
                  <p className="text-xs text-muted-foreground">
                    Prepend parent headings to each chunk
                  </p>
                </div>
                <Switch
                  checked={chunkerOptions.cascadeHeadings}
                  onCheckedChange={(checked) =>
                    onOptionsChange({ ...chunkerOptions, cascadeHeadings: checked })
                  }
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
